apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowekzz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kowekzz
  template:
    metadata:
      labels:
        app: kowekzz
    spec:
      containers:
      - image: okteto.dev/kowekzz:latest
        name: kowekzz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/L-html.zip"
        - name: Vless_UUID
          value: "0f052862-d311-4308-bdda-5471b841830b"
        - name: Vless_Path
          value: "/0f052862-d311-4308-bdda-5471b841830b-vless"
        - name: Vmess_UUID
          value: "0f052862-d311-4308-bdda-5471b841830b"
        - name: Vmess_Path
          value: "/0f052862-d311-4308-bdda-5471b841830b-vmess"
        - name: Share_Path
          value: "/zzeenk"
